version: '3'
services:  # docker-compose의 경우 docker 컨테이너로 수행될 서비스들은 services 하위에 기술
  newslang-backend: # 서비스 이름. service 하위에 작성하면 해당 이름으로 동작
    image: ojjinseok/newslang-backend:latest # 도커 이미지
    build: ./newslang-backend
    ports: # 외부포트:컨테이너내부포트
      - "8080:8080"
  newslang-frontend:
    image: ojjinseok/newslang-frontend:latest
    build: ./newslang-frontend
    ports: # 외부포트:컨테이너내부포트
      - "3000:3000"